var words = [
    { engWord:  'Bathroom', rusWord: ' Ванная' },
    { engWord:  'Wait', rusWord: ' Ждать' },
    { engWord:  'Ride', rusWord: ' Поездка' },
    { engWord:  'Sometimes', rusWord: ' Иногда' },
    { engWord:  'Hurry', rusWord: ' Спешить' },
    { engWord:  'After', rusWord: ' После' },
    { engWord: ' Wash', rusWord: ' Мыть' },
    { engWord: ' Already', rusWord: ' Уже' },
    { engWord: ' Listen', rusWord: ' Слушать' },
    { engWord: ' Seldom', rusWord: ' Редко' },
    { engWord: ' Divide', rusWord: ' Разбивать' },
    { engWord: ' According', rusWord: 'В соответствии  ' },
    { engWord: ' Although', rusWord: ' Несмотря на то что' },
    { engWord: ' Forehead', rusWord: ' Лоб' },
    { engWord: ' Ear', rusWord: ' Ухо' },
    { engWord: ' Chin', rusWord: ' Подбородок' },
    { engWord: ' Shoulder', rusWord: ' Плечо' },
    { engWord: ' Elbow', rusWord: ' Локоть' },
    { engWord: ' Forearm', rusWord: ' Предплечье' },
    { engWord: ' Wrist', rusWord: ' Запястье' },
    { engWord: ' Hand', rusWord: ' Кисть' },
    { engWord: ' Palm', rusWord: ' Ладонь' },
    { engWord: ' Finger', rusWord: ' Палец руки' },
    { engWord: ' Calf', rusWord: ' Голень/икра' },
    { engWord: ' Ankle', rusWord: ' Лодыжка' },
    { engWord: ' Heel', rusWord: ' Пятка' },
    { engWord: ' Head', rusWord: ' Голова' },
    { engWord: ' Neck', rusWord: ' Шея' },
    { engWord: ' Chest', rusWord: ' Грудь' },
    { engWord: ' Breast', rusWord: ' Грудь'},
    { engWord: ' Arm', rusWord: ' Рука' },
    { engWord: ' Waist', rusWord: ' Талия' },
    { engWord: ' Stomach', rusWord: ' Живот' },
    { engWord: ' Belly button', rusWord: ' Пупок' },
    { engWord: ' Pelvis', rusWord: ' Таз' },
    { engWord: ' Thigh', rusWord: ' Бедро' },
    { engWord: ' Leg', rusWord: ' Нога' },
    { engWord: ' Knee', rusWord: ' Колено' },
    { engWord: ' Shin', rusWord: ' Голень' },
    { engWord: ' Foot', rusWord: ' Нога' },
    { engWord: ' Toe', rusWord: ' Палец ноги' },
    { engWord: ' Wellies ', rusWord: ' Сапоги' },
    { engWord: ' Umbrella', rusWord: ' Зонтик' },
    { engWord: ' Usually ', rusWord: ' Как правило/обычно' },
    { engWord: ' Want', rusWord: ' Хотеть' },
    { engWord: ' Nearby ', rusWord: ' Рядом' },
    { engWord: ' Therefore', rusWord: ' Следовательно' },
    { engWord: ' Aunt', rusWord: ' Тётка' },
    { engWord: ' Shirt', rusWord: ' Рубашка' },
    { engWord: ' T-shirt', rusWord: ' Футболка' },
    { engWord: ' While ', rusWord: ' В то время как' },
    { engWord: ' Tie', rusWord: ' Галстук' },
    { engWord: ' Excited', rusWord: ' Восторг' },
    { engWord: ' Schedule/timetable ', rusWord: ' Список' },
    { engWord: ' Evening', rusWord: ' Вечер' },
    { engWord: ' Dinner ', rusWord: ' Ужин' },
    { engWord: ' Improve ', rusWord: ' Улучшать' },
    { engWord: ' Disappear', rusWord: ' Исчезать' },
    { engWord: ' Hugs ', rusWord: ' Объятия' },
    { engWord: ' Candle ', rusWord: ' Свеча' },
    { engWord: ' Escape ', rusWord: ' Побег' },
    { engWord: ' Weak', rusWord: ' Cлабый' },
    { engWord: ' Expectation ', rusWord: ' Ожидание ' },
    { engWord: ' Exhaust ', rusWord: ' Выхлоп ' },
    { engWord: ' Everyone ', rusWord: ' Любой ' },
    { engWord: ' Surrender ', rusWord: ' Сдача ' },
    { engWord: ' Shackle ', rusWord: ' Оковы ' },
    { engWord: ' Silence ', rusWord: ' Молчание ' },
    { engWord: ' Whatever ', rusWord: ' Все ' },
    { engWord: ' Whine ', rusWord: ' Ныть' },
    { engWord: ' Walk ', rusWord: ' Идти ' },
    { engWord: ' Cause ', rusWord: ' Причина ' },
    { engWord: ' Carry ', rusWord: ' Проводить ' },
    { engWord: ' Cave ', rusWord: ' Пещера ' },
    { engWord: ' Tangible ', rusWord: ' Материальный ' },
    { engWord: ' Trident ', rusWord: ' Трезубец ' },
    { engWord: ' Tumble ', rusWord: ' Упасть ' },
    { engWord: ' honest ', rusWord: ' честный ' },
    { engWord: ' earn ', rusWord: ' зарабатывать' },
    { engWord: ' thought ', rusWord: ' мысль' },
    { engWord: ' together ', rusWord: ' вместе' },
    { engWord: ' sofa ', rusWord: ' диван' },
    { engWord: ' newspaper ', rusWord: ' газета' },
    { engWord: ' paper ', rusWord: ' бумага' },
    { engWord: ' answer ', rusWord: ' ответ ' },
    { engWord: ' glad ', rusWord: ' довольный' },
    { engWord: ' something ', rusWord: ' нечто' },
    { engWord: ' here ', rusWord: ' вот' },
    { engWord: ' sold ', rusWord: ' продан' },
    { engWord: ' how ', rusWord: ' сейчас' },
    { engWord: ' now ', rusWord: ' как ' },
    { engWord: ' joy ', rusWord: ' радость' },
    { engWord: ' share ', rusWord: ' доля' },
    { engWord: ' to tidy ', rusWord: ' чтобы привести в порядок ' },
    { engWord: ' couple ', rusWord: ' пара ' },
    { engWord: ' treasure ', rusWord: ' сокровище ' },
    { engWord: ' discuss', rusWord: ' обсуждать' },
    { engWord: ' explore', rusWord: ' исследовать' },
    { engWord: ' answer', rusWord: ' ответ' },
    { engWord: ' bench', rusWord: ' скамейка' },
    { engWord: ' pupils', rusWord: ' ученики ' },
    { engWord: ' pupils', rusWord: ' зрачки ' },
    { engWord: ' exercising', rusWord: ' осуществление ' },
    { engWord: ' pretty', rusWord: ' cимпатичный ' },
    { engWord: ' neightbour', rusWord: ' сосед ' },
    { engWord: ' spend', rusWord: ' проводить ' },
    { engWord: ' pan pal', rusWord: ' кореш по переписке ' },
    { engWord: ' quite', rusWord: ' довольно ' },
    { engWord: ' servants', rusWord: ' слуга ' },
    { engWord: ' polite', rusWord: ' вежливый ' },
    { engWord: ' flat', rusWord: ' квартира' },
    { engWord: ' opinion', rusWord: ' мнение' },
    { engWord: ' before', rusWord: ' до' },
    { engWord: ' attitude', rusWord: ' отношение' },
    { engWord: ' butler', rusWord: ' дворецкий' },
    { engWord: ' lounge', rusWord: ' гостиная' },
    { engWord: ' poor', rusWord: ' бедные' },
    { engWord: ' useful', rusWord: ' полезным' },
    { engWord: ' magazine', rusWord: ' журнал' },
    { engWord: ' tired', rusWord: ' устала' },
    { engWord: ' motorway', rusWord: ' автомагистраль' },
    { engWord: 'need', rusWord: ' необходимость' },
    { engWord: ' fit', rusWord: ' поместиться' },
    { engWord: ' contain', rusWord: ' содержать' },
    { engWord: ' uptight', rusWord: ' встревоженный' },
    { engWord: ' own', rusWord: ' свой' },
    { engWord: ' behind', rusWord: ' позади' },
    { engWord: ' foyer', rusWord: ' фойе' },
    { engWord: ' scheming', rusWord: ' коварный' },
    { engWord: ' clapping', rusWord: ' аплодисменты' },
    { engWord: ' nose', rusWord: ' нос' },
    { engWord: ' commercial', rusWord: ' коммерческая' },
    { engWord: ' dagger', rusWord: ' кинжал' },
    { engWord: ' loom', rusWord: ' ткацкий станок, маячить' },
    { engWord: ' portentuous', rusWord: ' напыщенный' },
    { engWord: ' melt', rusWord: ' плавиться' },
    { engWord: ' morph', rusWord: ' превращаться' },
    { engWord: ' unfazed', rusWord: ' невозмутим' },
    { engWord: ' fairly', rusWord: ' довольно' },
    { engWord: ' cert', rusWord: ' верняк' },
    { engWord: ' sprawl', rusWord: ' растягиваться' },
    { engWord: ' compilation', rusWord: ' сборник' },
    { engWord: ' nebulous', rusWord: ' расплывчатый' },
    { engWord: ' engulf', rusWord: ' поглощать' },
    { engWord: ' recline', rusWord: ' откидывать' },
    { engWord: ' crest', rusWord: ' гребень' },
    { engWord: ' prefer', rusWord: ' предпочитать' }
];