var words = [
    {engWord: ' Nevertheless ', rusWord: ' Однако'},
    {engWord: ' Meantime ', rusWord: ' Тем временем'},
    {engWord: ' Although ', rusWord: ' Хотя'},
    {engWord: ' Frankly speaking ', rusWord: ' Откровенно говоря'},
    {engWord: ' So to speak ', rusWord: ' Так сказать'},
    {engWord: ' It goes without saying ', rusWord: ' Само собой разумеется'},
    {engWord: ' To put it mildly ', rusWord: ' Мягко говоря'},
    {engWord: ' At all ', rusWord: ' Вообще (в отрицательных предложениях)'},
    {engWord: ' In any case ', rusWord: ' В любом случае'},
    {engWord: ' So ', rusWord: ' Итак'},
    {engWord: ' Moreover ', rusWord: ' Кроме того'},
    {engWord: ' By the way ', rusWord: ' Кстати'},
    {engWord: ' Indeed ', rusWord: ' Действительно'},
    {engWord: ' Well ', rusWord: ' Xорошо'},
    {engWord: ' However ', rusWord: ' Однако'},
    {engWord: ' Telling the truth', rusWord: ' Говоря правду'},
    {engWord: ' Strictly speaking', rusWord: ' Строго говоря'},
    {engWord: ' To sum it up', rusWord: ' Подытоживая'},
    {engWord: ' Of course', rusWord: ' Конечно'},
    {engWord: ' Certainly ', rusWord: ' Безусловно'},
    {engWord: ' As far as I know', rusWord: ' Насколько мне известно'},
    {engWord: ' In other words', rusWord: '  Говоря другими словами'},
    {engWord: ' Probably ', rusWord: ' Возможно'},
    {engWord: ' To begin with', rusWord: '  Начнем с'},
    {engWord: ' I am hoping', rusWord: ' Я надеюсь'},
    {engWord: ' I am writing to say.', rusWord: ' Я пишу, чтобы сказать'},
    {engWord: ' I am really looking forward to.', rusWord: ' Я действительно с нетерпением жду '},
    {engWord: ' I really appreciated all your help.', rusWord: ' Я очень благодарен за Вашу помощь '},
    {engWord: '  I am interested in .', rusWord: ' Меня интересует'},
    {engWord: ' I don`t care about', rusWord: '  Меня не заботит (это)'},
    {engWord: ' I suppose', rusWord: ' Я полагаю,'},
    {engWord: ' In my view ', rusWord: ' С моей точки зрения'},
    {engWord: ' To my mind, In my opinion ', rusWord: ' По-моему '},
    {engWord: ' I am convinced', rusWord: ' Я убежден '},
    {engWord: ' Personally, I believe', rusWord: ' Лично я считаю, '},
    {engWord: ' Many people believe', rusWord: ' Многие люди считают, '},
    {engWord: ' As far as I remember', rusWord: ' Насколько я помню'},
    {engWord: ' From my point of view', rusWord: ' С моей точки зрения'},
    {engWord: ' However ', rusWord: ' Однако'},
    {engWord: ' Despite our…', rusWord: ' Несмотря на наши'},
    {engWord: ' In contrast to this', rusWord: '  В отличие от этого'},
    {engWord: ' On the other hand', rusWord: '  другой стороны'},
    {engWord: ' Compared to the other', rusWord: ' По сравнению с другими'},
    {engWord: ' is clearly different from', rusWord: '  явно отличается от'},
    {engWord: ' Definitely ', rusWord: ' Определенно'},
    {engWord: ' No wonder', rusWord: ' Неудивительно'},
    {engWord: ' In fact, (he is)', rusWord: ' По сути, (он является)'},
    {engWord: ' He used to say', rusWord: ' Он говорил'},
    {engWord: ' Not surprisingly', rusWord: '  Не удивительно'},
    {engWord: ' How about doing this', rusWord: ' Как насчет сделать это'},
    {engWord: ' Over the past two days', rusWord: ' За последние два дня'},
    {engWord: '  Apart from the negative impact that', rusWord: ' Помимо негативного воздействия, которое'},
    {engWord: ' One of the best thing about (the sport is).', rusWord: ' Одно из достоинств (спорта)'},
    {
        engWord: ' This might happen simply because (students)',
        rusWord: ' Это может произойти просто потому, что (студенты)'
    },
    {engWord: ' In total', rusWord: ' в общей сложности.'},
    {engWord: ' It is estimated', rusWord: ' По оценкам'},
    {engWord: ' If it is no longer', rusWord: ' Если это уже не'},
    {engWord: ' To sum up', rusWord: ' Подведем итоги'},
    {engWord: ' In addition', rusWord: ' В дополнительном'},
    {engWord: ' In conclusion', rusWord: ' В заключение'}

];