var words = [
    { engWord: ' honest ', rusWord: ' честный ' },
    { engWord: ' earn ', rusWord: ' зарабатывать' },
    { engWord: ' thought ', rusWord: ' мысль' },
    { engWord: ' together ', rusWord: ' вместе' },
    { engWord: ' sofa ', rusWord: ' диван' },
    { engWord: ' newspaper ', rusWord: ' газета' },
    { engWord: ' paper ', rusWord: ' бумага' },
    { engWord: ' glad ', rusWord: ' довольный' },
    { engWord: ' something ', rusWord: ' нечто' },
    { engWord: ' here ', rusWord: ' вот, здесь' },
    { engWord: ' sold ', rusWord: ' продан' },
    { engWord: ' now ', rusWord: ' сейчас' },
    { engWord: ' how ', rusWord: ' как ' },
    { engWord: ' joy ', rusWord: ' радость' },
    { engWord: ' share ', rusWord: ' доля' },
    { engWord: ' to tidy ', rusWord: ' чтобы привести в порядок ' },
    { engWord: ' couple ', rusWord: ' пара ' },
    { engWord: ' treasure ', rusWord: ' сокровище ' },
    { engWord: ' discuss', rusWord: ' обсуждать' },
    { engWord: ' explore', rusWord: ' исследовать' },
    { engWord: ' answer', rusWord: ' ответ' },
    { engWord: ' bench', rusWord: ' скамейка' },
    { engWord: ' pupils', rusWord: ' ученики, зрачки' },
    { engWord: ' exercising', rusWord: ' осуществление ' },
    { engWord: ' pretty', rusWord: ' cимпатичный ' },
    { engWord: ' neightbour', rusWord: ' сосед ' },
    { engWord: ' spend', rusWord: ' проводить ' },
    { engWord: ' pan pal', rusWord: ' кореш по переписке ' },
    { engWord: ' quite', rusWord: ' довольно ' },
    { engWord: ' servants', rusWord: ' слуга ' },
    { engWord: ' polite', rusWord: ' вежливый ' },
    { engWord: ' flat', rusWord: ' квартира' },
    { engWord: ' opinion', rusWord: ' мнение' },
    { engWord: ' before', rusWord: ' до' },
    { engWord: ' attitude', rusWord: ' отношение' },
    { engWord: ' butler', rusWord: ' дворецкий' },
    { engWord: ' lounge', rusWord: ' гостиная' },
    { engWord: ' poor', rusWord: ' бедные' },
    { engWord: ' useful', rusWord: ' полезным' },
    { engWord: ' magazine', rusWord: ' журнал' },
    { engWord: ' tired', rusWord: ' устала' },
    { engWord: ' motorway', rusWord: ' автомагистраль' },
    { engWord: ' need', rusWord: ' необходимость' },
    { engWord: ' fit', rusWord: ' поместиться' },
    { engWord: ' contain', rusWord: ' содержать' },
    { engWord: ' uptight', rusWord: ' встревоженный' },
    { engWord: ' own', rusWord: ' свой' },
    { engWord: ' behind', rusWord: ' позади' },
    { engWord: ' foyer', rusWord: ' фойе' },
    { engWord: ' scheming', rusWord: ' коварный' },
    { engWord: ' clapping', rusWord: ' аплодисменты' },
    { engWord: ' nose', rusWord: ' нос' },
    { engWord: ' commercial', rusWord: ' коммерческая' },
    { engWord: ' dagger', rusWord: ' кинжал' },
    { engWord: ' loom', rusWord: ' ткацкий станок, маячить' },
    { engWord: ' portentuous', rusWord: ' напыщенный' },
    { engWord: ' melt', rusWord: ' плавиться' },
    { engWord: ' morph', rusWord: ' превращаться' },
    { engWord: ' unfazed', rusWord: ' невозмутим' },
    { engWord: ' fairly', rusWord: ' довольно' },
    { engWord: ' cert', rusWord: ' верняк' },
    { engWord: ' sprawl', rusWord: ' растягиваться' },
    { engWord: ' compilation', rusWord: ' сборник' },
    { engWord: ' nebulous', rusWord: ' расплывчатый' },
    { engWord: ' engulf', rusWord: ' поглощать' },
    { engWord: ' recline', rusWord: ' откидывать' },
    { engWord: ' crest', rusWord: ' гребень' },
    { engWord: ' prefer', rusWord: ' предпочитать' }
    ];







